steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Configure Project
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|__APP_NAME__|$_APP_NAME|g' ./manifests/application.yaml
        sed -i 's|__ENV___|$_ENV|g' ./manifests/application.yaml
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: 'bash'
    args: [
      '-c',
      'docker build -t gcr.io/toel-342313/$_APP_NAME-$_ENV:latest . --build-arg="SSH_RSA_KEY=$$SSH_RSA_KEY"'
    ]
    secretEnv: ['SSH_GIT_CONFIG', 'SSH_RSA_KEY']

  - name: "gcr.io/cloud-builders/docker"
    id: Push Image
    args: ["push", "gcr.io/toel-342313/$_APP_NAME-$_ENV:latest"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: Deploy
    args:
    - run
    - --filename=./manifests/application.yaml
    - --image=gcr.io/toel-342313/$_APP_NAME-$_ENV:latest
    - --location=asia-southeast2-c
    - --cluster=$_CLUSTER_NAME-$_ENV

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SSH_GIT_CONFIG/versions/1
    env: 'SSH_GIT_CONFIG'
  - versionName: projects/$PROJECT_ID/secrets/SSH_RSA_KEY/versions/1
    env: 'SSH_RSA_KEY'
