// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/toel-app/template-server/src/internal/ping"
	"github.com/toel-app/template-server/src/pkg/config"
	"github.com/toel-app/template-server/src/pkg/db"
	"github.com/toel-app/template-server/src/pkg/logger"
)

// Injectors from wire.go:

func Wire() Application {
	loggerLogger := logger.NewLogger()
	configConfig := config.NewConfig(loggerLogger)
	database := db.NewMongoDB(configConfig, loggerLogger)
	closer := db.NewCloser(database)
	engine := NewRouter()
	controller := ping.NewController(engine)
	application := NewApp(loggerLogger, closer, controller)
	return application
}
